version: '3.8'

services:
  token-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "3001:3000"
      - "3002:3000"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - PORT=${PORT}
      - TOKEN_LIFETIME=${TOKEN_LIFETIME}
      - KEEP_ALIVE_THRESHOLD=${KEEP_ALIVE_THRESHOLD}
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:alpine
    restart: unless-stopped
